name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout code
      run: echo Hello, world!

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Build and Publish Web App
      run: msbuild .\dev\CustomMayd.Services.Serialization.sln /p:Configuration=Release
